#!/bin/bash
# --------------------------------------------------------------------------
# PocketKerbal - Run Script
# --------------------------------------------------------------------------
# License:   
# Copyright 2020 Erik Welsh
# Modified 2023 Rafe Neathery
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this 
# list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice, 
# this list of conditions and the following disclaimer in the documentation 
# and/or other materials provided with the distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its contributors 
# may be used to endorse or promote products derived from this software without 
# specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE 
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# --------------------------------------------------------------------------
# 
# Run Combination Lock in /var/lib/cloud9/ENGI301/Project_1
# 
# --------------------------------------------------------------------------

cd /var/lib/cloud9/ENGI301/Project_1

#sudo apt-get install python-serial
#sudo apt-get install python-cobs

./configure_pins.sh

dirs=(
    '/var/lib/cloud9/ENGI301/python/ht16k33:'
    '/var/lib/cloud9/ENGI301/python/button:'
    '/var/lib/cloud9/ENGI301/python/led:'
    '/var/lib/cloud9/ENGI301/python/potentiometer:'
    '/var/lib/cloud9/ENGI301/python/Joystick:'
    '/var/lib/cloud9/ENGI301/python/LCD:'
)

PYTHONPATH=$(IFS=; echo "${dirs[*]}") python3 Project_1_v2.py



